apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: image-validation-webhook-cert
  namespace: registry-system
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  secretName: image-validation-webhook-cert
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "image-validation-admission-svc.registry-system.svc"
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer