apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: image-validation-admission
  namespace: registry-system
  annotations:
    cert-manager.io/inject-ca-from: registry-system/image-validation-webhook-cert
webhooks:
  - name: image-validation-admission.tmax-cloud.github.com
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: image-validation-admission-svc
        namespace: registry-system
        port: 443
        path: "/validate"
      caBundle: ""
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources:
          - "pods"
    objectSelector:
      matchExpressions:
        - key: app
          operator: NotIn
          values:
            - image-validation-admission
    failurePolicy: Fail
    matchPolicy: Equivalent
